mods.extendedcrafting.TableCrafting.addShaped(0, <mekanism:energycube>.withTag({tier: 4, mekData: {energyStored: 1.7976931348623157E308}}), [
	[<thermalfoundation:geode>, <notenoughrtgs:rtg_californium_dense>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:dragonEgg>, <ore:ingotUltimate>, <ore:ingotUltimate>, <notenoughrtgs:rtg_californium_dense>, <thermalfoundation:geode>], 
	[<ore:ingotUltimate>, <ore:blockDraconiumAwakened>, <ore:gearInfinity>, <ore:gearInfinity>, <extrautils2:rainbowgenerator>, <ore:gearInfinity>, <ore:gearInfinity>, <ore:blockDraconiumAwakened>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <ore:plateInfinity>, <draconicevolution:awakened_core>, <extendedcrafting:material:40>, <draconicevolution:ender_energy_manipulator>, <extendedcrafting:material:40>, <draconicevolution:awakened_core>, <ore:plateInfinity>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <ore:plateInfinity>, <ore:blockCosmicNeutronium>, <wtfic2addon:advanced_condensator_reflector>, <wtfic2addon:te:10>, <wtfic2addon:advanced_condensator_reflector>, <ore:blockCosmicNeutronium>, <ore:plateInfinity>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <environmentaltech:solar_cont_5>, <mysticalagradditions:special:4>, <wtfic2addon:te:10>, <wtfic2addon:te:15>, <wtfic2addon:te:10>, <mysticalagradditions:special:4>, <environmentaltech:solar_cont_5>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <ore:plateInfinity>, <ore:blockCosmicNeutronium>, <wtfic2addon:advanced_condensator_reflector>, <wtfic2addon:te:10>, <wtfic2addon:advanced_condensator_reflector>, <ore:blockCosmicNeutronium>, <ore:plateInfinity>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <ore:plateInfinity>, <draconicevolution:awakened_core>, <extendedcrafting:material:40>, <draconicevolution:ender_energy_manipulator>, <extendedcrafting:material:40>, <draconicevolution:awakened_core>, <ore:plateInfinity>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <ore:blockDraconiumAwakened>, <ore:gearInfinity>, <ore:gearInfinity>, <environmentaltech:solar_cont_6>, <ore:gearInfinity>, <ore:gearInfinity>, <ore:blockDraconiumAwakened>, <ore:ingotUltimate>], 
	[<thermalfoundation:geode>, <notenoughrtgs:rtg_californium_dense>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:dragonEgg>, <ore:ingotUltimate>, <ore:ingotUltimate>, <notenoughrtgs:rtg_californium_dense>, <thermalfoundation:geode>]
]);

mods.extendedcrafting.TableCrafting.addShaped(0, <storagedrawers:upgrade_creative>, [
	[<industrialforegoing:black_hole_unit>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <industrialforegoing:black_hole_unit>], 
	[<storagedrawers:upgrade_storage:4>, <draconicevolution:draconium_chest>, <draconicevolution:draconium_chest>, <draconicevolution:draconium_chest>, <draconicevolution:draconium_chest>, <draconicevolution:draconium_chest>, <draconicevolution:draconium_chest>, <draconicevolution:draconium_chest>, <storagedrawers:upgrade_storage:4>], 
	[<storagedrawers:upgrade_storage:4>, <draconicevolution:draconium_chest>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <draconicevolution:draconium_chest>, <storagedrawers:upgrade_storage:4>], 
	[<storagedrawers:upgrade_storage:4>, <draconicevolution:draconium_chest>, <ore:ingotUltimate>, <thermalfoundation:geode>, <draconicevolution:chaotic_core>, <thermalfoundation:geode>, <ore:ingotUltimate>, <draconicevolution:draconium_chest>, <storagedrawers:upgrade_storage:4>], 
	[<storagedrawers:upgrade_storage:4>, <draconicevolution:draconium_chest>, <ore:ingotUltimate>, <extracells:storage.component:3>, <avaritia:singularity:14>, <extracells:storage.component:3>, <ore:ingotUltimate>, <draconicevolution:draconium_chest>, <storagedrawers:upgrade_storage:4>], 
	[<storagedrawers:upgrade_storage:4>, <draconicevolution:draconium_chest>, <ore:ingotUltimate>, <thermalfoundation:geode>, <draconicevolution:chaotic_core>, <thermalfoundation:geode>, <ore:ingotUltimate>, <draconicevolution:draconium_chest>, <storagedrawers:upgrade_storage:4>], 
	[<storagedrawers:upgrade_storage:4>, <draconicevolution:draconium_chest>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <draconicevolution:draconium_chest>, <storagedrawers:upgrade_storage:4>], 
	[<storagedrawers:upgrade_storage:4>, <draconicevolution:draconium_chest>, <draconicevolution:draconium_chest>, <draconicevolution:draconium_chest>, <draconicevolution:draconium_chest>, <draconicevolution:draconium_chest>, <draconicevolution:draconium_chest>, <draconicevolution:draconium_chest>, <storagedrawers:upgrade_storage:4>], 
	[<industrialforegoing:black_hole_unit>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <industrialforegoing:black_hole_unit>]
]);

mods.extendedcrafting.TableCrafting.addShaped(0, <mekanism:gastank>.withTag({tier: 4, mekData: {}}), [
	[<thermalfoundation:geode>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <thermalfoundation:geode>], 
	[<ore:ingotUltimate>, <ore:blockDraconiumAwakened>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mekanism:gastank>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <ore:blockDraconiumAwakened>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <mekanism:gastank>, <wtfic2addon:advanced_condensator_reflector>, <calculator:flawlessassembly>, <draconicevolution:chaotic_core>, <calculator:flawlessassembly>, <wtfic2addon:advanced_condensator_reflector>, <mekanism:gastank>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <mekanism:gastank>, <alchemistry:element:102>, <extracells:storage.component:17>, <extracells:storage.component:17>, <extracells:storage.component:17>, <alchemistry:element:102>, <mekanism:gastank>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <mekanism:gastank>, <draconicevolution:awakened_core>, <extracells:storage.component:17>, <avaritia:singularity:14>, <extracells:storage.component:17>, <draconicevolution:awakened_core>, <mekanism:gastank>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <mekanism:gastank>, <alchemistry:element:102>, <extracells:storage.component:17>, <extracells:storage.component:17>, <extracells:storage.component:17>, <alchemistry:element:102>, <mekanism:gastank>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <mekanism:gastank>, <wtfic2addon:advanced_condensator_reflector>, <calculator:flawlessassembly>, <draconicevolution:chaotic_core>, <calculator:flawlessassembly>, <wtfic2addon:advanced_condensator_reflector>, <mekanism:gastank>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <ore:blockDraconiumAwakened>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mekanism:gastank>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <ore:blockDraconiumAwakened>, <ore:ingotUltimate>], 
	[<thermalfoundation:geode>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <thermalfoundation:geode>]
]);
	recipes.addShapeless("Creative Gas Tank Reset", 
	<mekanism:gastank>.withTag({tier: 4, mekData: {}}), 
	[<mekanism:gastank>.withTag({tier: 4})]);


mods.extendedcrafting.TableCrafting.addShaped(0, <storagedrawers:upgrade_creative:1>, [
	[<thermalfoundation:geode>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <openblocks:heal>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <thermalfoundation:geode>], 
	[<ore:ingotUltimate>, <thermalexpansion:cache>.withTag({RSControl: 0 as byte, Item: {id: 49 as short, Count: 500000, Damage: 0 as short}, Creative: 0 as byte, Level: 4 as byte, Lock: 0 as byte}), <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <thermalexpansion:cache>.withTag({RSControl: 0 as byte, Item: {id: 10534 as short, Count: 500000, Damage: 0 as short}, Creative: 0 as byte, Level: 4 as byte, Lock: 0 as byte}), <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <avaritiaio:infinitecapacitor>, <mekanism:machineblock2:11>.withTag({tier: 4, mekData:{}}), <avaritiaio:infinitecapacitor>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <techreborn:quantum_chest>, <calculator:atomicmultiplier>, <storagedrawers:upgrade_creative>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <avaritiatweaks:enhancement_crystal>, <mekanism:gastank>.withTag({tier: 4, mekData: {}}), <avaritiatweaks:enhancement_crystal>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <tp:octuple_compressed_sugar_cane>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:compressed8xCobblestone>, <ore:ingotUltimate>], 
	[<thermalfoundation:geode>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <quark:rune:16>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <thermalfoundation:geode>]
]);

mods.extendedcrafting.TableCrafting.addShaped(0, <mekanism:machineblock2:11>.withTag({tier: 4, mekData:{}}), [
	[<thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "ironberryjuice", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte}), <forge:bucketfilled>.withTag({FluidName: "meat", Amount: 1000}), <forge:bucketfilled>.withTag({FluidName: "if.pink_slime", Amount: 1000}), <forge:bucketfilled>.withTag({FluidName: "sewage", Amount: 1000}), <forge:bucketfilled>.withTag({FluidName: "ender_distillation", Amount: 1000}), <forge:bucketfilled>.withTag({FluidName: "hootch", Amount: 1000}), <forge:bucketfilled>.withTag({FluidName: "fire_water", Amount: 1000}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: 1000}), <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "poison", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte})], 
	[<thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "ice", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte}), <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "refined_biofuel", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte})], 
	[<thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "biomass", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte}), <ore:ingotUltimate>, <draconicevolution:chaotic_core>, <extracells:storage.component:10>, <silentgems:miscblock:2>, <extracells:storage.component:10>, <draconicevolution:chaotic_core>, <ore:ingotUltimate>, <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "cloud_seed_concentrated", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte})], 
	[<thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "ic2uu_matter", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte}), <ore:ingotUltimate>, <draconicevolution:chaotic_core>, <thermalfoundation:geode>, <avaritia:singularity:14>, <thermalfoundation:geode>, <draconicevolution:chaotic_core>, <ore:ingotUltimate>, <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "liquidchorus", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte})], 
	[<thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "fluidglyceryl", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte}), <ore:ingotUltimate>, <cyclicmagic:crystallized_amber>, <ore:gearInfinity>, <extendedcrafting:material:13>, <ore:plateInfinity>, <cyclicmagic:crystallized_obsidian>, <ore:ingotUltimate>, <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "slop", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte})], 
	[<thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "vapor_of_levity", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte}), <ore:ingotUltimate>, <draconicevolution:chaotic_core>, <thermalfoundation:geode>, <ore:ingotInfinity>, <thermalfoundation:geode>, <draconicevolution:chaotic_core>, <ore:ingotUltimate>, <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "sludge", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte})], 
	[<thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "glass", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte}), <ore:ingotUltimate>, <draconicevolution:chaotic_core>, <extracells:storage.component:10>, <silentgems:miscblock:2>, <extracells:storage.component:10>, <draconicevolution:chaotic_core>, <ore:ingotUltimate>, <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "fluidheliumplasma", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte})], 
	[<thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "ethanol", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte}), <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "empoweredoil", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte})], 
	[<thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "milk_chocolate", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte}), <forge:bucketfilled>.withTag({FluidName: "mutagen", Amount: 1000}), <forge:bucketfilled>.withTag({FluidName: "menrilresin", Amount: 1000}), <forge:bucketfilled>.withTag({FluidName: "honey", Amount: 1000}), <forge:bucketfilled>.withTag({FluidName: "vasholine", Amount: 1000}), <forge:bucketfilled>.withTag({FluidName: "milk_jersey", Amount: 1000}), <forge:bucketfilled>.withTag({FluidName: "amber", Amount: 1000}), <forge:bucketfilled>.withTag({FluidName: "condensate_water", Amount: 1000}), <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "protein", Amount: 32000}, Level: 0 as byte, Lock: 0 as byte})]
]);
recipes.addShapeless("Creative Tank Reset", 
    <mekanism:machineblock2:11>.withTag({tier: 4, mekData: {}}), 
	[<mekanism:machineblock2:11>.withTag({tier: 4})]);

mods.extendedcrafting.TableCrafting.addShaped(0, <draconicevolution:draconium_capacitor:2>, [
	[<draconicevolution:chaotic_core>, <draconicevolution:dragon_heart>, null, null, <ore:blockDraconiumAwakened>, null, null, <draconicevolution:dragon_heart>, <draconicevolution:chaotic_core>], 
	[<draconicevolution:dragon_heart>, <draconicevolution:chaotic_core>, <draconicevolution:dragon_heart>, null, <ore:blockDraconiumAwakened>, null, <draconicevolution:dragon_heart>, <draconicevolution:chaotic_core>, <draconicevolution:dragon_heart>], 
	[null, <draconicevolution:dragon_heart>, <draconicevolution:chaotic_core>, <draconicevolution:dragon_heart>, <ore:blockDraconiumAwakened>, <draconicevolution:dragon_heart>, <draconicevolution:chaotic_core>, <draconicevolution:dragon_heart>, null], 
	[null, null, <draconicevolution:dragon_heart>, <draconicevolution:reactor_core>, <ore:blockDraconiumAwakened>, <draconicevolution:reactor_core>, <draconicevolution:dragon_heart>, null, null], 
	[<draconicevolution:chaotic_core>, <draconicevolution:chaotic_core>, <draconicevolution:chaotic_core>, <draconicevolution:chaotic_core>, <mekanism:energycube>.withTag({tier: 4, mekData: {energyStored: 1.7976931348623157E308}}), <draconicevolution:chaotic_core>, <draconicevolution:chaotic_core>, <draconicevolution:chaotic_core>, <draconicevolution:chaotic_core>], 
	[null, null, <draconicevolution:dragon_heart>, <draconicevolution:reactor_core>, <ore:blockDraconiumAwakened>, <draconicevolution:reactor_core>, <draconicevolution:dragon_heart>, null, null], 
	[null, <draconicevolution:dragon_heart>, <draconicevolution:chaotic_core>, <draconicevolution:dragon_heart>, <ore:blockDraconiumAwakened>, <draconicevolution:dragon_heart>, <draconicevolution:chaotic_core>, <draconicevolution:dragon_heart>, null], 
	[<draconicevolution:dragon_heart>, <draconicevolution:chaotic_core>, <draconicevolution:dragon_heart>, null, <ore:blockDraconiumAwakened>, null, <draconicevolution:dragon_heart>, <draconicevolution:chaotic_core>, <draconicevolution:dragon_heart>], 
	[<draconicevolution:chaotic_core>, <draconicevolution:dragon_heart>, null, null, <ore:blockDraconiumAwakened>, null, null, <draconicevolution:dragon_heart>, <draconicevolution:chaotic_core>]
]);

mods.extendedcrafting.TableCrafting.addShaped(0, <openblocks:heal>, [
	[<ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <minecraft:golden_apple:1>, <minecraft:golden_apple:1>, <minecraft:lingering_potion>.withTag({Potion: "cofhcore:healing4"}), <minecraft:golden_apple:1>, <minecraft:golden_apple:1>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <minecraft:golden_apple:1>, <deepmoblearning:pristine_matter_dragon>, <silentgems:craftingmaterial:31>, <deepmoblearning:pristine_matter_dragon>, <minecraft:golden_apple:1>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <draconicevolution:tool_upgrade:9>, <quark:enderdragon_scale>, <silentgems:craftingmaterial:28>, <quark:enderdragon_scale>, <draconicevolution:tool_upgrade:9>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <minecraft:golden_apple:1>, <deepmoblearning:pristine_matter_dragon>, <quark:soul_powder>, <deepmoblearning:pristine_matter_dragon>, <minecraft:golden_apple:1>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <minecraft:golden_apple:1>, <minecraft:golden_apple:1>, <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:instant_health", Duration: 1, Amplifier: 1}]}), <minecraft:golden_apple:1>, <minecraft:golden_apple:1>, <ore:ingotUltimate>], 
	[<ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:ingotUltimate>]
]);