import crafttweaker.item.IIngredient as IIngredient;
import crafttweaker.item.IItemStack as IItemStack;
import crafttweaker.oredict.IOreDict as IOreDict;
import crafttweaker.oredict.IOreDictEntry as IOreDictEntry;
#齿轮删除
val gears as IOreDictEntry[] = [

	<ore:gearIron>, 
	<ore:gearSteel>, 
	<ore:gearGold>, 
	<ore:gearMithril>, 
	<ore:gearTin>, 
	<ore:gearIridium>, 
	<ore:gearEmerald>, 
	<ore:gearNickel>, 
	<ore:gearBronze>, 
	<ore:gearPrudentium>, 
	<ore:gearPlatinum>, 
	<ore:gearCopper>, 
	<ore:gearAluminum>, 
	<ore:gearSignalum>, 
	<ore:gearConstantan>, 
	<ore:gearInvar>, 
	<ore:gearElectrum>, 
	<ore:gearSoulium>, 
	<ore:gearInsanium>, 
	<ore:gearQuartz>, 
	<ore:gearLapis>, 
	<ore:gearGlowstone>, 
	<ore:gearCoal>, 
	<ore:gearSupremium>, 
	<ore:gearCobalt>, 
	<ore:gearKnightslime>, 
	<ore:gearManyullyn>, 
	<ore:gearConductiveIron>, 
	<ore:gearSilicon>, 
	<ore:gearRefinedObsidian>, 
	<ore:gearSuperium>, 
	<ore:gearArdite>, 
	<ore:gearPigiron>, 
	<ore:gearDimensionalShard>, 
	<ore:gearEnderBiotite>, 
	<ore:gearChaos>, 
	<ore:gearZinc>, 
	<ore:gearLepidolite>, 
	<ore:gearDraconiumAwakened>, 
	<ore:gearDarkSteel>, 
	<ore:gearEndSteel>, 
	<ore:gearCrystalMatrix>, 
	<ore:gearRestonia>, 
	<ore:gearVoid>, 
	<ore:gearDiamatineEmpowered>, 
	<ore:gearDiamatine>, 
	<ore:gearEmeradicEmpowered>, 
	<ore:gearEnoriEmpowered>, 
	<ore:gearPalisEmpowered>, 
	<ore:gearCertusQuartz>, 
	<ore:gearFluix>, 
	<ore:gearYellorium>, 
	<ore:gearUranium>, 
	<ore:gearMagnesium>, 
	<ore:gearLithium>, 
	<ore:gearBoron>, 
	<ore:gearRedstoneAlloy>, 
	<ore:gearSoularium>, 
	<ore:gearDemonicMetal>, 
	<ore:gearOsmium>, 
	<ore:gearRefinedGlowstone>, 
	<ore:gearVibrantAlloy>, 
	<ore:gearEnori>, 
	<ore:gearPalis>, 
	<ore:gearEmeradic>, 
	<ore:gearPulsatingIron>, 
	<ore:gearElectricalSteel>, 
	<ore:gearEnergeticAlloy>, 
	<ore:gearPearl>, 
	<ore:gearAmmolite>, 
	<ore:gearOnyx>, 
	<ore:gearMorganite>, 
	<ore:gearMoonstone>, 
	<ore:gearChrysoprase>, 
	<ore:gearHeliodor>, 
	<ore:gearCosmicNeutronium>, 
	<ore:gearTanzanite>, 
	<ore:gearReinforcedIron>, 
	<ore:gearGarnet>, 
	<ore:gearAmethyst>, 
	<ore:gearEnrichedGold>
	
];

for oredict in gears {
	recipes.remove(oredict);
}
